[package]
name = "thorus-forge"
version = "0.1.0"
edition = "2024"
default-run = "animated-scene"

[dependencies]
approx = "0.5"
base64 = "0.22"
crossterm = "0.28"
glam = { version = "0.32.1", features = ["approx"] }
webp-animation = "0.10"

[dev-dependencies]
tempfile = "3"

[profile.release]
debug = true
